insert into dbo.tb_docente_especialidades (id_docente, id_especialidade, data_insercao, ativo) values(55,11, GETDATE(),1)
insert into dbo.tb_docente_especialidades (id_docente, id_especialidade, data_insercao, ativo) values(59,11, GETDATE(),1)
insert into dbo.tb_docente_especialidades (id_docente, id_especialidade, data_insercao, ativo) values(63,11, GETDATE(),1)
insert into dbo.tb_docente_especialidades (id_docente, id_especialidade, data_insercao, ativo) values(34,4, GETDATE(),1)
insert into dbo.tb_docente_especialidades (id_docente, id_especialidade, data_insercao, ativo) values(13,6, GETDATE(),1)
insert into dbo.tb_docente_especialidades (id_docente, id_especialidade, data_insercao, ativo) values(17,6, GETDATE(),1)
insert into dbo.tb_docente_especialidades (id_docente, id_especialidade, data_insercao, ativo) values(29,6, GETDATE(),1)
insert into dbo.tb_docente_especialidades (id_docente, id_especialidade, data_insercao, ativo) values(32,6, GETDATE(),1)
insert into dbo.tb_docente_especialidades (id_docente, id_especialidade, data_insercao, ativo) values(61,6, GETDATE(),1)
insert into dbo.tb_docente_especialidades (id_docente, id_especialidade, data_insercao, ativo) values(25,3, GETDATE(),1)
insert into dbo.tb_docente_especialidades (id_docente, id_especialidade, data_insercao, ativo) values(27,3, GETDATE(),1)
insert into dbo.tb_docente_especialidades (id_docente, id_especialidade, data_insercao, ativo) values(6,2, GETDATE(),1)
insert into dbo.tb_docente_especialidades (id_docente, id_especialidade, data_insercao, ativo) values(9,2, GETDATE(),1)
insert into dbo.tb_docente_especialidades (id_docente, id_especialidade, data_insercao, ativo) values(53,2, GETDATE(),1)
insert into dbo.tb_docente_especialidades (id_docente, id_especialidade, data_insercao, ativo) values(30,8, GETDATE(),1)
insert into dbo.tb_docente_especialidades (id_docente, id_especialidade, data_insercao, ativo) values(4,1, GETDATE(),1)
insert into dbo.tb_docente_especialidades (id_docente, id_especialidade, data_insercao, ativo) values(5,1, GETDATE(),1)
insert into dbo.tb_docente_especialidades (id_docente, id_especialidade, data_insercao, ativo) values(42,1, GETDATE(),1)
insert into dbo.tb_docente_especialidades (id_docente, id_especialidade, data_insercao, ativo) values(49,7, GETDATE(),1)

Update tb_docente_especialidades set id_jornada = 1 Where id_docente in(12, 15, 16, 20, 22, 24, 26, 31, 47, 56, 58, 62, 64)
Update tb_docente_especialidades set id_jornada = 2 Where id_docente in(1, 3, 4, 7, 11, 13, 18 , 19, 25, 28, 30, 33, 37, 43, 45, 46, 48, 51, 52, 55, 57, 59, 60 )
Update tb_docente_especialidades set id_jornada = 3 Where id_docente in(2, 5, 6, 8, 9, 10, 14, 17, 21, 23, 27, 29, 30, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 49, 50, 54, 61, 63, 65)
