insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(1,'8853126','ADRIANA APARECIDA MARAGONI DIAS', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(2,'8288054','ANA MARIA DA SILVA', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(3,'8853061','ANA VITORIA DE OLIVEIRA ALVES', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(4,'7842881','ANGELO PELACHINI VALLE', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(5,'6789021','AVANI BARRETO MATOS', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(6,'7833661','BIANCA MELZI DE DOMENICIS LUCCHESI', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(7,'8421421','CARLOS FRANCISCO ALMEIDA DA SILVA', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(8,'8215898','CASSIA FERREIRA DO PRADO', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(9,'7183283','CINTIA MARIA JARDO MARTINS', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(10,'8083959','CINTIA SANTOS RODRIGUES FIALHO', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(11,'8854670','CRISTIANA NASCIMENTO DA CRUZ', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(12,'7820593','DAIANE FARINE CHAGAS', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(13,'7912854','DANIELA AUXILIADORA DIAS AIOSI', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(14,'7725485','DEBORA JULIANA ALVES MANOEL', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(15,'5724180','ELIANE DA SILVA SATURNINO', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(16,'7337787','ELIAS JOSÉ DE ALMEIDA', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(17,'7163932','ELISANGELA BARBOSA MENEZES', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(18,'8852928','FABIANE SAMPAIO DOS SANTOS', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(19,'8855986','FERNANDA CRISTINA MENDES COSTA', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(20,'8816026','FERNANDA SILVA DA COSTA', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(21,'8441456','GABRIELA DIAS LEITE', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(22,'7829841','GABRIELA DOS SANTOS VIEIRA DA SILVA', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(23,'8028061','GABRIELA SANTOS CORREIA ARAUJO', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(24,'8879702','HALON PEDREIRA GURGEL', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(25,'8548889','HUMBERTO DE ASSIS SILVERIO', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(26,'6123147','HUMBERTO LUIZ DE JESUS', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(27,'6882561','IRACI DOS SANTOS', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(28,'8853860','IVANETE REIMBERG MATHIAS DOS SANTOS', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(29,'8562407','JULIANA LIMA FONSECA', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(30,'7914784','KAMILA MONTEIRO SANTOS', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(32,'8901911','LINO BATISTA DE SOUZA', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(33,'6759343','LIVIA COELHO DA SILVA', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(34,'8546860','LUCIANA FERNANDES MATOS', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(35,'8511098','LUCIANA FIORATO', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(36,'6768369','MARA APARECIDA DO NASCIMENTO', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(37,'6911323','MARCELA DE PINA BERGAMINE', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(38,'7136846','MARCELO DA SILVA PENNA', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(40,'7229054','MARCIA DA CRUZ ISLAS', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(41,'7347472','MARGARETH DE FARIA', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(42,'7532181','MARIA APARECIDA DE LIMA', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(43,'3186491','MARIA DA SILVA BRUSCHI', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(44,'7821174','MARLI LOPES DE ARAUJO', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(45,'8467510','MILENA APARECIDA ANDRADE ILARIO', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(46,'8515743','MONALISA CARDOSO DE SOUSA', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(47,'7768541','NARA LUCIA SANTOS DE OLIVEIRA', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(48,'8251371','ODAIR FERREIRA SANTOS', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(49,'7721803','OSMIR SANTOS MACEDO', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(50,'7947321','PATRICIA GOMES AMORIM DE SOUZA', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(51,'8426104','RENATA SANTOS SIQUEIRA VERAS', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(52,'7927878','RICARDO DE LUCENA BEZERRA', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(53,'8854939','RITA APARECIDA MONTEIRO SANGUINO', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(54,'7864841','ROBERTA KELLY DA SILVA HIRAOKA', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(55,'8825629','SERGIO HENRIQUE VALADÃO', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(56,'5026067','ROSA LUISA COLOMBO', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(57,'8855684','ROSANGELA BORBA DE LUCENA', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(58,'8357421','SANDRA APARECIDA NALIATO GONÇALVES', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(59,'8082847','SHEYLA FERNANDES', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(60,'8032173','SHIRLEN KAREN COSTA', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(61,'8855862','SINVALDO DIAS DA SILVA', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(62,'7271328','SIMONE CRISTINA DE OLIVEIRA', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(63,'8078998','TABATA CRISTINA UCHOA VALENTIM', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(64,'7591578','TELMA DE LOURDES COELHO', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(65,'8416630','THAIS MARIA GOMES', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(66,'7951841','VANESSA SANTOS DE MORAIS', getdate(),1)
insert into dbo.tb_docente (numero, rf, nome, data_insercao, ativo) values(67,'7386893','ZENAIDE LIMA CLARO', getdate(),1)
			
			